# Generated by Django 6.0 on 2026-01-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student'),
        ),
    ]
