# Generated by Django 6.0 on 2026-01-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_studentprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='date_of_joining',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
