# Generated by Django 6.0 on 2026-01-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_teacherprofile_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='date_of_joining',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
