# Generated by Django 6.0 on 2026-01-19 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('assessment_type', models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('midterm', 'Midterm'), ('final', 'Final Exam')], max_length=20)),
                ('marks_obtained', models.FloatField()),
                ('max_marks', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='enrollment.enrollment')),
            ],
        ),
    ]
