# Generated by Django 6.0 on 2026-01-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
